swagger: "2.0"

info:
  version: "1.0.0"
  title: "Polling Booth"
  description: "API of Polling Booth"

schemes:
- "http"
host: "localhost:3000"
basePath: "/"

tags:
- name: "user"

paths:
  /verification-code:
    post:
      tags:
        - "user"
      summary: "Fetchs verification code"
      parameters:
      - in: "formData"
        name: "email"
        required: true
      responses:
        200:
          description: "Success"
          example: "{ code: 200, message: 'success' }"
        1001:
          description: "Too frequent requests"
          example: "{ code: 1001, message: 'too frequent requests' }"
        422:
          description: "Unprocessable entity"

  /users/register:
    post:
      tags:
      - "user"
      summary: "Register"
      parameters:
      - in: "formData"
        name: "email"
        required: true
      - in: "formData"
        name: "fullname"
        required: true
      - in: "formData"
        name: "password"
        required: true
      - in: "formData"
        name: "verificationCode"
        required: true
      responses:
        200:
          description: "Success"
          example: "{ code: 200, message: 'success' }"
        1001:
          description: "Verification code is incorrect"
          example: "{ code: 1001, message: 'verification code is incorrect' }"
        1002:
          description: "email address already in use"
          example: "{ code: 1002, message: 'email address already in use' }"
        422:
          description: "Unprocessable entity"

  /users/login:
    post:
      tags:
        - "users"
      summary: "Login"
      parameters:
      - in: "formData"
        name: "email"
        required: true
      - in: "formData"
        name: "password"
        required: true
      responses:
        200:
          description: "Success"
          example: "{ code: 200, message: 'success', data: { token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoxMjMsImlhdCI6MTQ5MTQ3NTQyNCwiZXhwIjoxNDkxNDc1NDg0fQ.hYNC4qFAyhZClmPaLixfN137d41R2CFk1xPlfLK10JU' } }"
        1001:
          description: "User does not exist"
          example: "{ code: 1001, message: 'user does not exist' }"
        1002:
          description: "Password is incorrect"
          example: "{ code: 1002, message: 'password is incorrect' }"
        422:
          description: "Unprocessable entity"
